# Generated by Django 5.1.2 on 2026-03-14 11:43

import Categories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categories', '0003_alter_category_is_listed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=Categories.models.get_cloudinary_storage, upload_to='category_images/'),
        ),
    ]
