# Generated by Django 5.1.2 on 2026-03-31 11:48

from django.db import migrations

def create_wallets(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Wallet = apps.get_model('Wallet', 'Wallet')
    for user in User.objects.all():
        Wallet.objects.get_or_create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_wallets),
    ]
