# Generated by Django 5.1.2 on 2026-03-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_alter_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
