# Generated by Django 5.1.2 on 2026-04-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0009_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='return_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
