# Generated by Django 5.1.2 on 2026-04-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0010_orderitem_return_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('return_requested', 'Return Requested'), ('return_rejected', 'Return Rejected'), ('returned', 'Returned')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('canceled', 'Canceled'), ('return_requested', 'Return Requested'), ('return_rejected', 'Return Rejected'), ('returned', 'Returned')], default='pending', max_length=50),
        ),
    ]
