# Generated by Django 5.1.2 on 2026-03-14 11:43

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_alter_product_offer_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(null=True, storage=Products.models.get_cloudinary_storage, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, storage=Products.models.get_cloudinary_storage, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, storage=Products.models.get_cloudinary_storage, upload_to='products/'),
        ),
    ]
